Feat/141 download btn
Typiqally/epsilon pull request #103
Opened 2023-06-14 10:02 UTC by WouterPennings

- Added download button component for the competence document
 - Discussed with Eline about styling, and followed styling guidde

If you want to see the button, you can add it to the performance dashboard

2023-06-14 14:05 UTC, Typiqally requested changes

2023-06-14 14:05 UTC, Typiqally commented on Epsilon.Host.Frontend/src/components/CompetenceDocumentDownloadButton.vue
> +<style>
Use scoped, and maybe SCSS?

2023-06-14 14:05 UTC, Typiqally commented on Epsilon.Host.Frontend/src/components/CompetenceDocumentDownloadButton.vue
> +            src="@/assets/download-icon.png"
If possible, use font awesome

2023-06-14 14:05 UTC, Typiqally commented on Epsilon.Host.Frontend/src/components/CompetenceDocumentDownloadButton.vue
> +        style="display: flex; justify-content: space-between">
Make class for this

2023-06-16 08:31 UTC, NealGeilen requested changes

2023-06-16 08:31 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/assets/download-icon.png
Please use a existing font lib

2023-06-23 08:38 UTC, NealGeilen requested changes

2023-06-23 08:38 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/CompetenceDocumentDownloadButton.vue
> +    async function downloadCompetenceDocument() {
Please use the `API` class for requests 
https://github.com/Typiqally/epsilon/blob/develop/Epsilon.Host.Frontend/src/logic/Api.ts

2023-06-23 08:39 UTC, NealGeilen commented
Also, please fix the GitHub action error

2023-06-23 10:16 UTC, NealGeilen approved these changes

2023-06-27 07:43 UTC, Typiqally approved these changes
Very nice button, I like it.

2023-06-27 07:43 UTC, merged