Feat/word export
Typiqally/epsilon pull request #36
Opened 2022-10-27 20:11 UTC by NealGeilen

Adding the functionality to the project for exporting to "Word" files aka ".docx"

This is mostly done as a test to see what it takes to create word documents within .NET. 
I wanted to test this so that there is a base when we want to start the development of a "competence document generator"

2022-10-27 20:37 UTC, Typiqally commented
Nice work, I'll take a look when you are ready for review :D

2022-10-27 21:02 UTC, NealGeilen commented
I was thinking, is it still needed to have a pdf export format? 

I just don't think that there is a need for it. Especially looking at the fact that you can't edit a pdf document. With this a user can only copy the contents of the document. And you can already do that with the other export formats.

2022-10-28 15:23 UTC, Typiqally commented
> I was thinking, is it still needed to have a pdf export format? #27
> 
> I just don't think that there is a need for it. Especially looking at the fact that you can't edit a pdf document. With this a user can only copy the contents of the document. And you can already do that with the other export formats. 

That's fair, you can remove it from the issue if you want.

2022-11-04 10:35 UTC, Typiqally requested changes
Nice work, left some small review comments. I was also wondering if you spent time on Linux compatible formats such as OTD?

2022-11-04 10:35 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +                        row.Cells[ 0 ].Paragraphs[ 0 ].Append( outcome.Title + " " +  ShortDescription(ConvertHtmlToRaw(outcome.Description)) );
Can you reformat the spaces around the array index and parenthesis? They do not conform to the coding style Also for the rest of this class.

2022-11-04 10:35 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +    private string OutcomeToText(double? result)
Maybe we can change this into a public helper function, maybe an extension method for OutcomeResult (e.g., outcomeResult.toUsgo() or something similar)

2022-11-04 10:35 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +    private static string ShortDescription(string description)
We should also start moving these methods to a helper function of sorts.

2022-11-05 09:11 UTC, NealGeilen commented
> I was also wondering if you spent time on Linux compatible formats such as OTD?

At this moment I cant find a .NET lib that supports this format.

2022-11-07 08:29 UTC, Typiqally commented
> > I was also wondering if you spent time on Linux compatible formats such as OTD?
> 
> At this moment I cant find a .NET lib that supports this format.

That's fine, I believe many Word editing tools support the MS Word format on Linux anyway.

2022-11-07 08:34 UTC, Typiqally requested changes
I'm really liking the helper functions, nicely done, still have some minor changes requests

2022-11-07 08:34 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +                    worksheet.Cells[index, 0] = new Cell(outcome.Title + " " +  outcome.ShortDescription());
Can you use string interpolation here?

2022-11-07 08:34 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +        using (DocX document = DocX.Create(_options.FormattedOutputName+".docx"))
String interpolation here as well

2022-11-07 08:34 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +                table.Rows[ 0 ].Cells[ 0 ].Paragraphs[ 0 ].Append("KPI");
Maybe for convenience, just format this document using the following shortcut

- Rider: CTRL + ALT + L
- Visual Studio: CTRL + K, CTRL + F
- VS Code: ALT + Shift + F

2022-11-07 15:42 UTC, merged