Feat/42 use the open xml sdk to create export document
Typiqally/epsilon pull request #45
Opened 2022-11-29 10:58 UTC by NealGeilen

2022-11-29 11:01 UTC, NealGeilen commented
Sorry for the Git mess. Can't really find what went wrong here.

2022-11-29 11:02 UTC, NealGeilen commented
@Typiqally Could you test the word export feature on a Mac with this branch. 
The code is a mess but i just wanted to know if it works.

2022-11-29 11:08 UTC, Typiqally commented
> Sorry for the Git mess. Can't really find what went wrong here.

Maybe you didn't update your master branch?

2022-11-29 11:09 UTC, NealGeilen commented
> > Sorry for the Git mess. Can't really find what went wrong here.
> 
> Maybe you didn't update your master branch on local?

I thought I did, But it is possible. idk

2022-11-29 12:09 UTC, Typiqally commented
I get the following errors on macOS

```
Error 1
Description: The element has unexpected child element 'http://schemas.openxmlformats.org/wordprocessingml/2006/main:tr'. List of possible elements expected: <http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeStart>.
ErrorType: Schema
Node: DocumentFormat.OpenXml.Wordprocessing.Table
Path: /w:document[1]/w:body[1]/w:tbl[3]
Part: /word/document.xml
-------------------------------------------
Error 2
Description: The element has unexpected child element 'http://schemas.openxmlformats.org/wordprocessingml/2006/main:tr'. List of possible elements expected: <http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeStart>.
ErrorType: Schema
Node: DocumentFormat.OpenXml.Wordprocessing.Table
Path: /w:document[1]/w:body[1]/w:tbl[2]
Part: /word/document.xml
-------------------------------------------
Error 3
Description: The element has unexpected child element 'http://schemas.openxmlformats.org/wordprocessingml/2006/main:tr'. List of possible elements expected: <http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeStart>.
ErrorType: Schema
Node: DocumentFormat.OpenXml.Wordprocessing.Table
Path: /w:document[1]/w:body[1]/w:tbl[1]
Part: /word/document.xml
-------------------------------------------
count=3
Error 1
Description: The element has unexpected child element 'http://schemas.openxmlformats.org/wordprocessingml/2006/main:tr'. List of possible elements expected: <http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeStart>.
ErrorType: Schema
Node: DocumentFormat.OpenXml.Wordprocessing.Table
Path: /w:document[1]/w:body[1]/w:tbl[3]
Part: /word/document.xml
-------------------------------------------
Error 2
Description: The element has unexpected child element 'http://schemas.openxmlformats.org/wordprocessingml/2006/main:tr'. List of possible elements expected: <http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeEnd>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeStart>,<http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeEnd>,<http://schema [...]

2022-11-29 12:21 UTC, NealGeilen commented
Could you share the gibberish? 

I have the same errors, the table still has its headers on windows. (The goal of POC)

2022-11-29 12:23 UTC, Typiqally commented
[Epsilon-Export-29112022130627.docx](https://github.com/Typiqally/epsilon/files/10112963/Epsilon-Export-29112022130627.docx)

2022-11-29 12:30 UTC, NealGeilen commented
> [Epsilon-Export-29112022130627.docx](https://github.com/Typiqally/epsilon/files/10112963/Epsilon-Export-29112022130627.docx)

So, At my side its correct 
![image](https://user-images.githubusercontent.com/44571222/204529462-41acef12-7281-434c-a535-2dd47dd55375.png)


You are opening the file with word?

2022-11-29 12:31 UTC, Typiqally commented
I'm opening the file with [Pages](https://www.apple.com/pages/), the standard processor for Word documents on macOS.

2022-11-29 15:56 UTC, NealGeilen commented
> I'm opening the file with [Pages](https://www.apple.com/pages/), the standard processor for Word documents on macOS.

Could you try again with the latest update? I implemented an example script from the Microsoft docs now. 

The issue now is that the file can be generated by a mac. It only does not show it correctly in Pages. but it has support for the format. And why it won't show is something I don't follow.  Word can read, Google Docs can read it. and my mobile can read the format. I can't find out why Pages won't accept it.

2022-11-29 18:26 UTC, Typiqally commented
Same issue, see screenshot:

<img width="275" alt="Screenshot 2022-11-29 at 19 25 20" src="https://user-images.githubusercontent.com/12190745/204614852-e7df31de-6e59-4c90-9ba2-3020161a0dde.png">

2022-11-29 18:56 UTC, NealGeilen commented
> Same issue, see screenshot:
> 
> <img alt="Screenshot 2022-11-29 at 19 25 20" width="275" src="https://user-images.githubusercontent.com/12190745/204614852-e7df31de-6e59-4c90-9ba2-3020161a0dde.png">
> 
> Maybe specifying a set width for the columns will work?

Yes. That's indeed something that I skipped for a POC. 
Do we need to test this also for Linux? or is this good enough to continue development?

2022-11-30 07:43 UTC, Typiqally commented
> > Same issue, see screenshot:
> > <img alt="Screenshot 2022-11-29 at 19 25 20" width="275" src="https://user-images.githubusercontent.com/12190745/204614852-e7df31de-6e59-4c90-9ba2-3020161a0dde.png">
> > Maybe specifying a set width for the columns will work?
> 
> Yes. That's indeed something that I skipped for a POC. Do we need to test this also for Linux? or is this good enough to continue development?
> 
> For me this is good enough and a clear sign that it will work.

I feel like if it works for macOS then it will probably work on Linux as well since they are both based on Unix. Unless they are using very specific Linux instructions for some reason, but I doubt that since it is really just a fancy XML generator.

2023-03-07 10:01 UTC, NealGeilen commented
@Typiqally The PR is now complete and up to date with the main branch.

2023-03-15 09:27 UTC, Typiqally requested changes

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +    private static TableProperties GetTableProperties()
Could be a constant

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +            Table table = new Table();
We are using 'var' everywhere, so here should be the same

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +                TableRow row = new TableRow();
Use 'var'

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +            Cell newCell = new Cell() { CellReference = cellReference };
We are using 'var' everywhere, so here should be the same

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +        Sheet sheet = new Sheet() { Id = relationshipId, SheetId = sheetId, Name = module.Name };
We are using 'var' everywhere, so here should be the same

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +        WorksheetPart newWorksheetPart = workbookPart.AddNewPart<WorksheetPart>();
We are using 'var' everywhere, so here should be the same

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +        Cell cell = InsertCellInWorksheet(columnName, rowIndex, worksheetPart);
We are using 'var' everywhere, so here should be the same

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +        WorkbookPart workbookpart = spreadsheetDocument.AddWorkbookPart();
We are using 'var' everywhere, so here should be the same

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +            WorksheetPart worksheetPart = InsertWorksheet(module, workbookpart);
We are using 'var' everywhere, so here should be the same

2023-03-15 09:27 UTC, Typiqally commented on Epsilon/Export/ExportDataPackager.cs
> +                            Name = alignments[assignmentId!].Name,
We should start thinking about nullability here, see ! symbol

2023-03-17 13:19 UTC, NealGeilen commented on Epsilon/Export/Exporters/WordModuleExporter.cs
> +    private static TableProperties GetTableProperties()
I can't get this fixed without causing an error when running the application.

2023-03-17 16:00 UTC, Typiqally commented on Epsilon/Export/Exporters/ExcelModuleExporter.cs
> +            }
I think this would make it a bit cleaner

2023-03-17 16:01 UTC, Typiqally approved these changes

2023-03-22 12:18 UTC, Typiqally approved these changes

2023-03-22 12:25 UTC, merged