Feat/58 unit testing poc
Typiqally/epsilon pull request #73
Opened 2023-03-15 08:56 UTC by SyntaxSven

2023-03-15 09:32 UTC, Typiqally requested changes

2023-03-15 09:32 UTC, Typiqally commented on Epsilon.Tests/Epsilon.Tests.csproj
> +    <PackageReference Include="xunit" Version="2.4.2" />
Is there any reason to use xunit over NUnit over here?

2023-03-15 09:32 UTC, Typiqally commented on Epsilon.Canvas.Tests/Services/AssignmentHttpServiceTests.cs
> +        public async Task GetAll_ReturnsAssignments()
Can we use acceptance criteria notation here? Given... when... then

2023-03-15 09:32 UTC, Typiqally commented on Epsilon.Tests/ExportDataPackagerTests.cs
> +        public async Task GetExportData_ReturnsExportData()
Given... when... then

2023-03-15 09:32 UTC, Typiqally commented on Epsilon.Tests/Exporters/ExcelModuleExporterTests.cs
> +        public async Task Export_WithValidData_ReturnsStreamWithExpectedContent()
Given... when... then

2023-03-17 13:23 UTC, NealGeilen commented
![image](https://user-images.githubusercontent.com/44571222/225917183-27abf0c6-d1e7-4f7b-993c-f7634138274a.png)
Tests run in Rider

2023-03-28 07:53 UTC, NealGeilen approved these changes

2023-03-28 07:55 UTC, Typiqally approved these changes

2023-03-28 07:56 UTC, merged