Poc/performance dashboard decaying average frontend
Typiqally/epsilon pull request #86
Opened 2023-04-20 18:51 UTC by NealGeilen

#83 needs to be merged first.

2023-04-20 18:55 UTC, NealGeilen commented
When selecting a term, the decaying average does not change. 
Is this something that we want? Or do we want that the decaying average to change depending on the selected term?
This will change the results and thus create confusion when things are "masterd" 

@Typiqally @jendafojtik

2023-04-20 20:06 UTC, Typiqally commented
> When selecting a term, the decaying average does not change. Is this something that we want? Or do we want that the decaying average to change depending on the selected term? This will change the results and thus create confusion when things are "masterd"
> 
> @Typiqally @jendafojtik

The decaying average should change when selecting a term. It is important that it reflects what the decaying average would have looked like at that time in the term, so that a teacher (or student) can essentially go back in time.

2023-04-21 18:22 UTC, jendafojtik commented
@Typiqally @NealGeilen I'll look over the formula this weekend and make sure to have it worked out by Monday!

2023-05-08 22:08 UTC, NealGeilen commented
![Recording 2023-05-09 000602](https://user-images.githubusercontent.com/44571222/236948880-c2fe9416-f13f-49f3-8dfc-6767717b6185.gif)

2023-05-15 12:36 UTC, NealGeilen commented
@Typiqally Ready for review

2023-05-17 15:31 UTC, Typiqally requested changes

2023-05-17 15:31 UTC, Typiqally commented on Epsilon.Abstractions/Epsilon.Abstractions.csproj
> +
Usually this gets added if this directory is empty, if it is empty, please remove it

2023-05-17 15:31 UTC, Typiqally commented on Epsilon.Abstractions/Model/OutcomeResult.cs
> +public abstract record OutcomeResult
Can you put the required properties in the constructor

2023-05-17 15:31 UTC, Typiqally commented on Epsilon.Host.Frontend/src/components/PersonalDevelopmentGraph.vue
> +watch(() => loadChartData())
Can you move this under `onMounted`?

2023-05-17 15:31 UTC, Typiqally commented on Epsilon.Host.Frontend/src/logic/DecayingAverageLogic.ts
> +    private static GetDecayingAverageFromOneOutcomeType(
Naming convention, please use camel case

2023-05-17 15:31 UTC, Typiqally commented on Epsilon.Host.Frontend/src/logic/DecayingAverageLogic.ts
> +    private static GetDecayingAverageForAllOutcomes(
Camel case

2023-05-17 15:31 UTC, Typiqally commented on Epsilon.Host.Frontend/src/logic/DecayingAverageLogic.ts
> +    public static GetAverageTaskOutcomeScores(
Camel case

2023-05-17 15:31 UTC, Typiqally commented on Epsilon.Host.Frontend/src/logic/DecayingAverageLogic.ts
> +    public static GetAverageSkillOutcomeScores(
Camel case

2023-05-17 15:31 UTC, Typiqally requested changes
Well done, some minor things

2023-05-18 18:56 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/PersonalDevelopmentGraph.vue
> +watch(() => loadChartData())
Apparently the watch is not triggered when placed inside the mount function

2023-05-23 09:11 UTC, Typiqally approved these changes

2023-05-23 09:11 UTC, merged